-- Add aliases column for stock search
-- Stores common names/aliases generated by AI (e.g. ["Google", "谷歌", "Alphabet"])
ALTER TABLE watchlist_stocks ADD COLUMN IF NOT EXISTS aliases TEXT[] DEFAULT '{}';
